name: Grade assignment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle pycodestyle pylint pytest
      - name: Check documentation
        run: |
          pydocstyle
      - name: Check code style
        run: |
          pycodestyle
      - name: Lint with pylint
        run: |
          # you can use comments
          pylint *.py
